name          'geosense-safekeep'
version       '0.1.0'
source        'https://github.com/geosense/puppet-safekeep'
author        'Jan Škoda, Geosense'
license       'GNU GPL v3'
summary       'Module for managing safekeep backups.'
description   ''
project_page  'https://github.com/geosense/puppet-safekeep'

dependency 'puppetlabs/stdlib'
